### ISSUE TITLE
fix Pico TTS incompatibilities with 64-bit

### ISSUE THREAD

**Issue by thestinger** [AndroidHardeningArchive/bugtracker#487]

**Comment by parrotgeek1** [comment]
whatever you do, do NOT fork the Android Pico TTS/SVOX repo onto github

some former employee is mad at SVOX and is DMCAing anything with Pico TTS (which he wrote?) in  it

https://github.com/github/dmca/search?p=2&q=svox&type=&utf8=%E2%9C%93

**Comment by thestinger** [comment]
It's been at https://github.com/CopperheadOS/platform_external_svox for a long time and hasn't been an issue. It doesn't make any difference to us if this is on GitHub. Either way, it's an AOSP component used in CopperheadOS.

**Comment by parrotgeek1** [comment]
Sorry, never mind.

**Comment by yavorpap** [comment]
The https://github.com/CopperheadOS/platform_external_svox repository is unavailable as of now.
Building Cooperhead is impossible, at least for Nexus 5X (failing at the `repo sync` step, due to the missing repo). I'd say this is critical as of now. Please advise.

The DMCA is more than a week old: https://github.com/github/dmca/blob/0bbbbe9350c521e87b9679641c507ab46c3cd273/2017/2017-09-28-CambridgeMobile.md (/copperhead)

**Comment by thestinger** [comment]
It's not used by the current development branch or stable tags. It's off-topic for this issue anyway.

**Comment by yavorpap** [comment]
So it's safe to remove `platform_external_svox` from `.repo/manifests/default.xml`?

**Comment by thestinger** [comment]
Pico has been dead for so long that I don't care about this anymore. It should be replaced rather than fixed at this point. I'm not going to be including it in GrapheneOS anymore since it was removed from AOSP. I'm interested in alternatives to it though, but most seem just as unmaintained.
