### ISSUE TITLE
Buttons not visible in CopperheadOS Keyboard Settings

### ISSUE THREAD

**Issue by xbtc-im** [AndroidHardeningArchive/bugtracker#834]
They still work though, still not visible. Only on Pixel 2 (XL), on the old Pixel is fine.
See screenshot.
![screenshot_20180118-122108](https://user-images.githubusercontent.com/32508652/35095439-5f72eb76-fc40-11e7-9513-cc37d4abf58b.png)

**Comment by thestinger** [comment]
It only happens on the Pixel 2 XL, not the Pixel. We'll likely wait for them to fix it upstream if ever unless someone works on it. AOSP bugs like this aren't something we tend to do work on other than applying a known fix.

**Comment by xbtc-im** [comment]
Oh it's an upstream bug. It's of low importance anyway, just thought to mention it

**Comment by thestinger** [comment]
I'll keep an eye out for a fix in master.

**Comment by thestinger** [comment]
This also appears to be a problem for the Launcher3 settings.

**Comment by thestinger** [comment]
Long press homepage -> Home settings.

**Comment by thestinger** [comment]
@xbtc-im Do you remember what this is about? I can't tell what the issue was anymore. I'm going through all these new issues to see if they need to be migrated to the new issue tracker for GrapheneOS.

https://github.com/GrapheneOS/os_issue_tracker/issues

The keyboard and launcher settings do seem fine on the Pixel 2 now.
