### ISSUE TITLE
Clock/Alarm stops giving notifications after recent update.

### ISSUE THREAD

**Issue by kittenpirate** [AndroidHardeningArchive/bugtracker#867]
The default Clock app is not giving notifications anymore after recent updates. I can no longer turn off an alarm using the notification bar because of this. I am using angler and have been recieving all the newest updates for over a year. It seems to me certain apps that I cannot uninstall, like Clock & Etar, are not updating with new updates. Please advise, thanks.

**Comment by thestinger** [comment]
This is just an archive of my past work. I'm not involved in CopperheadOS and my work is temporarily stalled while I work out the way of continuing it.

**Comment by thestinger** [comment]
I essentially need to start building it all up again with Android 9.0 and I won't be able to support the Nexus 5X and 6P. The reason you aren't getting updates to those apps is because there are no longer updates since June, and system apps can't be removed or upgraded with a build signed with another key. I recommend moving to the stock OS for now.

**Comment by thestinger** [comment]
I essentially need to start building it all up again with Android 9.0 and I won't be able to support the Nexus 5X and 6P. The reason you aren't getting updates to those apps is because there are no longer updates since June, and system apps can't be removed or upgraded with a build signed with another key. I recommend moving to the stock OS for now and then another device once it's EOL since no one can do full security updates after that.

**Comment by kittenpirate** [comment]
Are you saying that you handed CopperheadOS development over to someone else or are you just stopping work on it until you are able to continue? When you say "stock OS" are you refering to the unsafe version that ships with the devce, not CopperheadOS? What exactly stalled your work with Android 8? Sorry for the questions, but my technical expertise only goes so far.

**Comment by thestinger** [comment]
> Are you saying that you handed CopperheadOS development over to someone else

I was pushed out of the company. Copperhead / CopperheadOS don't have anything to do with me anymore other than the fact that I wrote all of the code in the past.

> When you say "stock OS" are you refering to the unsafe version that ships with the devce, not CopperheadOS?

I'm suggesting using the OS that ships on the device and has factory images available from Google.
